version: '3.8'
services:
  fantasy-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./fpl_knowledge_db:/app/fpl_knowledge_db
    environment:
      - EURI_API_KEY=${EURI_API_KEY}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: